<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Collection;

class CitySeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $cities = [
            ['governorate_id' => 1, 'name' => '15 مايو'],
            ['governorate_id' => 1, 'name' => 'الازبكية'],
            ['governorate_id' => 1, 'name' => 'البساتين'],
            ['governorate_id' => 1, 'name' => 'التبين'],
            ['governorate_id' => 1, 'name' => 'الخليفة'],
            ['governorate_id' => 1, 'name' => 'الدراسة'],
            ['governorate_id' => 1, 'name' => 'الدرب الاحمر'],
            ['governorate_id' => 1, 'name' => 'الزاوية الحمراء'],
            ['governorate_id' => 1, 'name' => 'الزيتون'],
            ['governorate_id' => 1, 'name' => 'الساحل'],
            ['governorate_id' => 1, 'name' => 'السلام'],
            ['governorate_id' => 1, 'name' => 'السيدة زينب'],
            ['governorate_id' => 1, 'name' => 'الشرابية'],
            ['governorate_id' => 1, 'name' => 'مدينة الشروق'],
            ['governorate_id' => 1, 'name' => 'الظاهر'],
            ['governorate_id' => 1, 'name' => 'العتبة'],
            ['governorate_id' => 1, 'name' => 'القاهرة الجديدة'],
            ['governorate_id' => 1, 'name' => 'المرج'],
            ['governorate_id' => 1, 'name' => 'عزبة النخل'],
            ['governorate_id' => 1, 'name' => 'المطرية'],
            ['governorate_id' => 1, 'name' => 'المعادى'],
            ['governorate_id' => 1, 'name' => 'المعصرة'],
            ['governorate_id' => 1, 'name' => 'المقطم'],
            ['governorate_id' => 1, 'name' => 'المنيل'],
            ['governorate_id' => 1, 'name' => 'الموسكى'],
            ['governorate_id' => 1, 'name' => 'النزهة'],
            ['governorate_id' => 1, 'name' => 'الوايلى'],
            ['governorate_id' => 1, 'name' => 'باب الشعرية'],
            ['governorate_id' => 1, 'name' => 'بولاق'],
            ['governorate_id' => 1, 'name' => 'جاردن سيتى'],
            ['governorate_id' => 1, 'name' => 'حدائق القبة'],
            ['governorate_id' => 1, 'name' => 'حلوان'],
            ['governorate_id' => 1, 'name' => 'دار السلام'],
            ['governorate_id' => 1, 'name' => 'شبرا'],
            ['governorate_id' => 1, 'name' => 'طره'],
            ['governorate_id' => 1, 'name' => 'عابدين'],
            ['governorate_id' => 1, 'name' => 'عباسية'],
            ['governorate_id' => 1, 'name' => 'عين شمس'],
            ['governorate_id' => 1, 'name' => 'مدينة نصر'],
            ['governorate_id' => 1, 'name' => 'مصر الجديدة'],
            ['governorate_id' => 1, 'name' => 'مصر القديمة'],
            ['governorate_id' => 1, 'name' => 'منشية ناصر'],
            ['governorate_id' => 1, 'name' => 'مدينة بدر'],
            ['governorate_id' => 1, 'name' => 'مدينة العبور'],
            ['governorate_id' => 1, 'name' => 'وسط البلد'],
            ['governorate_id' => 1, 'name' => 'الزمالك'],
            ['governorate_id' => 1, 'name' => 'قصر النيل'],
            ['governorate_id' => 1, 'name' => 'الرحاب'],
            ['governorate_id' => 1, 'name' => 'القطامية'],
            ['governorate_id' => 1, 'name' => 'مدينتي'],
            ['governorate_id' => 1, 'name' => 'روض الفرج'],
            ['governorate_id' => 1, 'name' => 'شيراتون'],
            ['governorate_id' => 1, 'name' => 'الجمالية'],
            ['governorate_id' => 1, 'name' => 'العاشر من رمضان'],
            ['governorate_id' => 1, 'name' => 'الحلمية'],
            ['governorate_id' => 1, 'name' => 'النزهة الجديدة'],
            ['governorate_id' => 1, 'name' => 'العاصمة الإدارية'],
            ['governorate_id' => 2, 'name' => 'الجيزة'],
            ['governorate_id' => 2, 'name' => 'السادس من أكتوبر'],
            ['governorate_id' => 2, 'name' => 'الشيخ زايد'],
            ['governorate_id' => 2, 'name' => 'الحوامدية'],
            ['governorate_id' => 2, 'name' => 'البدرشين'],
            ['governorate_id' => 2, 'name' => 'الصف'],
            ['governorate_id' => 2, 'name' => 'أطفيح'],
            ['governorate_id' => 2, 'name' => 'العياط'],
            ['governorate_id' => 2, 'name' => 'الباويطي'],
            ['governorate_id' => 2, 'name' => 'منشأة القناطر'],
            ['governorate_id' => 2, 'name' => 'أوسيم'],
            ['governorate_id' => 2, 'name' => 'كرداسة'],
            ['governorate_id' => 2, 'name' => 'أبو النمرس'],
            ['governorate_id' => 2, 'name' => 'كفر غطاطي'],
            ['governorate_id' => 2, 'name' => 'منشأة البكاري'],
            ['governorate_id' => 2, 'name' => 'الدقى'],
            ['governorate_id' => 2, 'name' => 'العجوزة'],
            ['governorate_id' => 2, 'name' => 'الهرم'],
            ['governorate_id' => 2, 'name' => 'الوراق'],
            ['governorate_id' => 2, 'name' => 'امبابة'],
            ['governorate_id' => 2, 'name' => 'بولاق الدكرور'],
            ['governorate_id' => 2, 'name' => 'الواحات البحرية'],
            ['governorate_id' => 2, 'name' => 'العمرانية'],
            ['governorate_id' => 2, 'name' => 'المنيب'],
            ['governorate_id' => 2, 'name' => 'بين السرايات'],
            ['governorate_id' => 2, 'name' => 'الكيت كات'],
            ['governorate_id' => 2, 'name' => 'المهندسين'],
            ['governorate_id' => 2, 'name' => 'فيصل'],
            ['governorate_id' => 2, 'name' => 'أبو رواش'],
            ['governorate_id' => 2, 'name' => 'حدائق الأهرام'],
            ['governorate_id' => 2, 'name' => 'الحرانية'],
            ['governorate_id' => 2, 'name' => 'حدائق اكتوبر'],
            ['governorate_id' => 2, 'name' => 'صفط اللبن'],
            ['governorate_id' => 2, 'name' => 'القرية الذكية'],
            ['governorate_id' => 2, 'name' => 'ارض اللواء'],
            ['governorate_id' => 3, 'name' => 'ابو قير'],
            ['governorate_id' => 3, 'name' => 'الابراهيمية'],
            ['governorate_id' => 3, 'name' => 'الأزاريطة'],
            ['governorate_id' => 3, 'name' => 'الانفوشى'],
            ['governorate_id' => 3, 'name' => 'الدخيلة'],
            ['governorate_id' => 3, 'name' => 'السيوف'],
            ['governorate_id' => 3, 'name' => 'العامرية'],
            ['governorate_id' => 3, 'name' => 'اللبان'],
            ['governorate_id' => 3, 'name' => 'المفروزة'],
            ['governorate_id' => 3, 'name' => 'المنتزه'],
            ['governorate_id' => 3, 'name' => 'المنشية'],
            ['governorate_id' => 3, 'name' => 'الناصرية'],
            ['governorate_id' => 3, 'name' => 'امبروزو'],
            ['governorate_id' => 3, 'name' => 'باب شرق'],
            ['governorate_id' => 3, 'name' => 'برج العرب'],
            ['governorate_id' => 3, 'name' => 'ستانلى'],
            ['governorate_id' => 3, 'name' => 'سموحة'],
            ['governorate_id' => 3, 'name' => 'سيدى بشر'],
            ['governorate_id' => 3, 'name' => 'شدس'],
            ['governorate_id' => 3, 'name' => 'غيط العنب'],
            ['governorate_id' => 3, 'name' => 'فلمينج'],
            ['governorate_id' => 3, 'name' => 'فيكتوريا'],
            ['governorate_id' => 3, 'name' => 'كامب شيزار'],
            ['governorate_id' => 3, 'name' => 'كرموز'],
            ['governorate_id' => 3, 'name' => 'محطة الرمل'],
            ['governorate_id' => 3, 'name' => 'مينا البصل'],
            ['governorate_id' => 3, 'name' => 'العصافرة'],
            ['governorate_id' => 3, 'name' => 'العجمي'],
            ['governorate_id' => 3, 'name' => 'بكوس'],
            ['governorate_id' => 3, 'name' => 'بولكلي'],
            ['governorate_id' => 3, 'name' => 'كليوباترا'],
            ['governorate_id' => 3, 'name' => 'جليم'],
            ['governorate_id' => 3, 'name' => 'المعمورة'],
            ['governorate_id' => 3, 'name' => 'المندرة'],
            ['governorate_id' => 3, 'name' => 'محرم بك'],
            ['governorate_id' => 3, 'name' => 'الشاطبي'],
            ['governorate_id' => 3, 'name' => 'سيدي جابر'],
            ['governorate_id' => 3, 'name' => 'الساحل الشمالي'],
            ['governorate_id' => 3, 'name' => 'الحضرة'],
            ['governorate_id' => 3, 'name' => 'العطارين'],
            ['governorate_id' => 3, 'name' => 'سيدي كرير'],
            ['governorate_id' => 3, 'name' => 'الجمرك'],
            ['governorate_id' => 3, 'name' => 'المكس'],
            ['governorate_id' => 3, 'name' => 'مارينا'],
            ['governorate_id' => 4, 'name' => 'المنصورة'],
            ['governorate_id' => 4, 'name' => 'طلخا'],
            ['governorate_id' => 4, 'name' => 'ميت غمر'],
            ['governorate_id' => 4, 'name' => 'دكرنس'],
            ['governorate_id' => 4, 'name' => 'أجا'],
            ['governorate_id' => 4, 'name' => 'منية النصر'],
            ['governorate_id' => 4, 'name' => 'السنبلاوين'],
            ['governorate_id' => 4, 'name' => 'الكردي'],
            ['governorate_id' => 4, 'name' => 'بني عبيد'],
            ['governorate_id' => 4, 'name' => 'المنزلة'],
            ['governorate_id' => 4, 'name' => 'تمي الأمديد'],
            ['governorate_id' => 4, 'name' => 'الجمالية'],
            ['governorate_id' => 4, 'name' => 'شربين'],
            ['governorate_id' => 4, 'name' => 'المطرية'],
            ['governorate_id' => 4, 'name' => 'بلقاس'],
            ['governorate_id' => 4, 'name' => 'ميت سلسيل'],
            ['governorate_id' => 4, 'name' => 'جمصة'],
            ['governorate_id' => 4, 'name' => 'محلة دمنة'],
            ['governorate_id' => 4, 'name' => 'نبروه'],
            ['governorate_id' => 5, 'name' => 'الغردقة'],
            ['governorate_id' => 5, 'name' => 'رأس غارب'],
            ['governorate_id' => 5, 'name' => 'سفاجا'],
            ['governorate_id' => 5, 'name' => 'القصير'],
            ['governorate_id' => 5, 'name' => 'مرسى علم'],
            ['governorate_id' => 5, 'name' => 'الشلاتين'],
            ['governorate_id' => 5, 'name' => 'حلايب'],
            ['governorate_id' => 5, 'name' => 'الدهار'],
            ['governorate_id' => 6, 'name' => 'دمنهور'],
            ['governorate_id' => 6, 'name' => 'كفر الدوار'],
            ['governorate_id' => 6, 'name' => 'رشيد'],
            ['governorate_id' => 6, 'name' => 'إدكو'],
            ['governorate_id' => 6, 'name' => 'أبو المطامير'],
            ['governorate_id' => 6, 'name' => 'أبو حمص'],
            ['governorate_id' => 6, 'name' => 'الدلنجات'],
            ['governorate_id' => 6, 'name' => 'المحمودية'],
            ['governorate_id' => 6, 'name' => 'الرحمانية'],
            ['governorate_id' => 6, 'name' => 'إيتاي البارود'],
            ['governorate_id' => 6, 'name' => 'حوش عيسى'],
            ['governorate_id' => 6, 'name' => 'شبراخيت'],
            ['governorate_id' => 6, 'name' => 'كوم حمادة'],
            ['governorate_id' => 6, 'name' => 'بدر'],
            ['governorate_id' => 6, 'name' => 'وادي النطرون'],
            ['governorate_id' => 6, 'name' => 'النوبارية الجديدة'],
            ['governorate_id' => 6, 'name' => 'النوبارية'],
            ['governorate_id' => 7, 'name' => 'الفيوم'],
            ['governorate_id' => 7, 'name' => 'الفيوم الجديدة'],
            ['governorate_id' => 7, 'name' => 'طامية'],
            ['governorate_id' => 7, 'name' => 'سنورس'],
            ['governorate_id' => 7, 'name' => 'إطسا'],
            ['governorate_id' => 7, 'name' => 'إبشواي'],
            ['governorate_id' => 7, 'name' => 'يوسف الصديق'],
            ['governorate_id' => 7, 'name' => 'الحادقة'],
            ['governorate_id' => 7, 'name' => 'اطسا'],
            ['governorate_id' => 7, 'name' => 'الجامعة'],
            ['governorate_id' => 7, 'name' => 'السيالة'],
            ['governorate_id' => 8, 'name' => 'طنطا'],
            ['governorate_id' => 8, 'name' => 'المحلة الكبرى'],
            ['governorate_id' => 8, 'name' => 'كفر الزيات'],
            ['governorate_id' => 8, 'name' => 'زفتى'],
            ['governorate_id' => 8, 'name' => 'السنطة'],
            ['governorate_id' => 8, 'name' => 'قطور'],
            ['governorate_id' => 8, 'name' => 'بسيون'],
            ['governorate_id' => 8, 'name' => 'سمنود'],
            ['governorate_id' => 9, 'name' => 'الإسماعيلية'],
            ['governorate_id' => 9, 'name' => 'فايد'],
            ['governorate_id' => 9, 'name' => 'القنطرة شرق'],
            ['governorate_id' => 9, 'name' => 'القنطرة غرب'],
            ['governorate_id' => 9, 'name' => 'التل الكبير'],
            ['governorate_id' => 9, 'name' => 'أبو صوير'],
            ['governorate_id' => 9, 'name' => 'القصاصين الجديدة'],
            ['governorate_id' => 9, 'name' => 'نفيشة'],
            ['governorate_id' => 9, 'name' => 'الشيخ زايد'],
            ['governorate_id' => 10, 'name' => 'شبين الكوم'],
            ['governorate_id' => 10, 'name' => 'مدينة السادات'],
            ['governorate_id' => 10, 'name' => 'منوف'],
            ['governorate_id' => 10, 'name' => 'سرس الليان'],
            ['governorate_id' => 10, 'name' => 'أشمون'],
            ['governorate_id' => 10, 'name' => 'الباجور'],
            ['governorate_id' => 10, 'name' => 'قويسنا'],
            ['governorate_id' => 10, 'name' => 'بركة السبع'],
            ['governorate_id' => 10, 'name' => 'تلا'],
            ['governorate_id' => 10, 'name' => 'الشهداء'],
            ['governorate_id' => 11, 'name' => 'المنيا'],
            ['governorate_id' => 11, 'name' => 'المنيا الجديدة'],
            ['governorate_id' => 11, 'name' => 'العدوة'],
            ['governorate_id' => 11, 'name' => 'مغاغة'],
            ['governorate_id' => 11, 'name' => 'بني مزار'],
            ['governorate_id' => 11, 'name' => 'مطاي'],
            ['governorate_id' => 11, 'name' => 'سمالوط'],
            ['governorate_id' => 11, 'name' => 'المدينة الفكرية'],
            ['governorate_id' => 11, 'name' => 'ملوي'],
            ['governorate_id' => 11, 'name' => 'دير مواس'],
            ['governorate_id' => 11, 'name' => 'ابو قرقاص'],
            ['governorate_id' => 11, 'name' => 'ارض سلطان'],
            ['governorate_id' => 12, 'name' => 'بنها'],
            ['governorate_id' => 12, 'name' => 'قليوب'],
            ['governorate_id' => 12, 'name' => 'شبرا الخيمة'],
            ['governorate_id' => 12, 'name' => 'القناطر الخيرية'],
            ['governorate_id' => 12, 'name' => 'الخانكة'],
            ['governorate_id' => 12, 'name' => 'كفر شكر'],
            ['governorate_id' => 12, 'name' => 'طوخ'],
            ['governorate_id' => 12, 'name' => 'قها'],
            ['governorate_id' => 12, 'name' => 'العبور'],
            ['governorate_id' => 12, 'name' => 'الخصوص'],
            ['governorate_id' => 12, 'name' => 'شبين القناطر'],
            ['governorate_id' => 12, 'name' => 'مسطرد'],
            ['governorate_id' => 13, 'name' => 'الخارجة'],
            ['governorate_id' => 13, 'name' => 'باريس'],
            ['governorate_id' => 13, 'name' => 'موط'],
            ['governorate_id' => 13, 'name' => 'الفرافرة'],
            ['governorate_id' => 13, 'name' => 'بلاط'],
            ['governorate_id' => 13, 'name' => 'الداخلة'],
            ['governorate_id' => 14, 'name' => 'السويس'],
            ['governorate_id' => 14, 'name' => 'الجناين'],
            ['governorate_id' => 14, 'name' => 'عتاقة'],
            ['governorate_id' => 14, 'name' => 'العين السخنة'],
            ['governorate_id' => 14, 'name' => 'فيصل'],
            ['governorate_id' => 15, 'name' => 'أسوان'],
            ['governorate_id' => 15, 'name' => 'أسوان الجديدة'],
            ['governorate_id' => 15, 'name' => 'دراو'],
            ['governorate_id' => 15, 'name' => 'كوم أمبو'],
            ['governorate_id' => 15, 'name' => 'نصر النوبة'],
            ['governorate_id' => 15, 'name' => 'كلابشة'],
            ['governorate_id' => 15, 'name' => 'إدفو'],
            ['governorate_id' => 15, 'name' => 'الرديسية'],
            ['governorate_id' => 15, 'name' => 'البصيلية'],
            ['governorate_id' => 15, 'name' => 'السباعية'],
            ['governorate_id' => 15, 'name' => 'ابوسمبل السياحية'],
            ['governorate_id' => 15, 'name' => 'مرسى علم'],
            ['governorate_id' => 16, 'name' => 'أسيوط'],
            ['governorate_id' => 16, 'name' => 'أسيوط الجديدة'],
            ['governorate_id' => 16, 'name' => 'ديروط'],
            ['governorate_id' => 16, 'name' => 'منفلوط'],
            ['governorate_id' => 16, 'name' => 'القوصية'],
            ['governorate_id' => 16, 'name' => 'أبنوب'],
            ['governorate_id' => 16, 'name' => 'أبو تيج'],
            ['governorate_id' => 16, 'name' => 'الغنايم'],
            ['governorate_id' => 16, 'name' => 'ساحل سليم'],
            ['governorate_id' => 16, 'name' => 'البداري'],
            ['governorate_id' => 16, 'name' => 'صدفا'],
            ['governorate_id' => 17, 'name' => 'بني سويف'],
            ['governorate_id' => 17, 'name' => 'بني سويف الجديدة'],
            ['governorate_id' => 17, 'name' => 'الواسطى'],
            ['governorate_id' => 17, 'name' => 'ناصر'],
            ['governorate_id' => 17, 'name' => 'إهناسيا'],
            ['governorate_id' => 17, 'name' => 'ببا'],
            ['governorate_id' => 17, 'name' => 'الفشن'],
            ['governorate_id' => 17, 'name' => 'سمسطا'],
            ['governorate_id' => 17, 'name' => 'الاباصيرى'],
            ['governorate_id' => 17, 'name' => 'مقبل'],
            ['governorate_id' => 18, 'name' => 'بورسعيد'],
            ['governorate_id' => 18, 'name' => 'بورفؤاد'],
            ['governorate_id' => 18, 'name' => 'العرب'],
            ['governorate_id' => 18, 'name' => 'حى الزهور'],
            ['governorate_id' => 18, 'name' => 'حى الشرق'],
            ['governorate_id' => 18, 'name' => 'حى الضواحى'],
            ['governorate_id' => 18, 'name' => 'حى المناخ'],
            ['governorate_id' => 18, 'name' => 'حى مبارك'],
            ['governorate_id' => 19, 'name' => 'دمياط'],
            ['governorate_id' => 19, 'name' => 'دمياط الجديدة'],
            ['governorate_id' => 19, 'name' => 'رأس البر'],
            ['governorate_id' => 19, 'name' => 'فارسكور'],
            ['governorate_id' => 19, 'name' => 'الزرقا'],
            ['governorate_id' => 19, 'name' => 'السرو'],
            ['governorate_id' => 19, 'name' => 'الروضة'],
            ['governorate_id' => 19, 'name' => 'كفر البطيخ'],
            ['governorate_id' => 19, 'name' => 'عزبة البرج'],
            ['governorate_id' => 19, 'name' => 'ميت أبو غالب'],
            ['governorate_id' => 19, 'name' => 'كفر سعد'],
            ['governorate_id' => 20, 'name' => 'الزقازيق'],
            ['governorate_id' => 20, 'name' => 'العاشر من رمضان'],
            ['governorate_id' => 20, 'name' => 'منيا القمح'],
            ['governorate_id' => 20, 'name' => 'بلبيس'],
            ['governorate_id' => 20, 'name' => 'مشتول السوق'],
            ['governorate_id' => 20, 'name' => 'القنايات'],
            ['governorate_id' => 20, 'name' => 'أبو حماد'],
            ['governorate_id' => 20, 'name' => 'القرين'],
            ['governorate_id' => 20, 'name' => 'ههيا'],
            ['governorate_id' => 20, 'name' => 'أبو كبير'],
            ['governorate_id' => 20, 'name' => 'فاقوس'],
            ['governorate_id' => 20, 'name' => 'الصالحية الجديدة'],
            ['governorate_id' => 20, 'name' => 'الإبراهيمية'],
            ['governorate_id' => 20, 'name' => 'ديرب نجم'],
            ['governorate_id' => 20, 'name' => 'كفر صقر'],
            ['governorate_id' => 20, 'name' => 'أولاد صقر'],
            ['governorate_id' => 20, 'name' => 'الحسينية'],
            ['governorate_id' => 20, 'name' => 'صان الحجر القبلية'],
            ['governorate_id' => 20, 'name' => 'منشأة أبو عمر'],
            ['governorate_id' => 21, 'name' => 'الطور'],
            ['governorate_id' => 21, 'name' => 'شرم الشيخ'],
            ['governorate_id' => 21, 'name' => 'دهب'],
            ['governorate_id' => 21, 'name' => 'نويبع'],
            ['governorate_id' => 21, 'name' => 'طابا'],
            ['governorate_id' => 21, 'name' => 'سانت كاترين'],
            ['governorate_id' => 21, 'name' => 'أبو رديس'],
            ['governorate_id' => 21, 'name' => 'أبو زنيمة'],
            ['governorate_id' => 21, 'name' => 'رأس سدر'],
            ['governorate_id' => 22, 'name' => 'كفر الشيخ'],
            ['governorate_id' => 22, 'name' => 'وسط البلد كفر الشيخ'],
            ['governorate_id' => 22, 'name' => 'دسوق'],
            ['governorate_id' => 22, 'name' => 'فوه'],
            ['governorate_id' => 22, 'name' => 'مطوبس'],
            ['governorate_id' => 22, 'name' => 'برج البرلس'],
            ['governorate_id' => 22, 'name' => 'بلطيم'],
            ['governorate_id' => 22, 'name' => 'مصيف بلطيم'],
            ['governorate_id' => 22, 'name' => 'الحامول'],
            ['governorate_id' => 22, 'name' => 'بيلا'],
            ['governorate_id' => 22, 'name' => 'الرياض'],
            ['governorate_id' => 22, 'name' => 'سيدي سالم'],
            ['governorate_id' => 22, 'name' => 'قلين'],
            ['governorate_id' => 22, 'name' => 'سيدي غازي'],
            ['governorate_id' => 23, 'name' => 'مرسى مطروح'],
            ['governorate_id' => 23, 'name' => 'الحمام'],
            ['governorate_id' => 23, 'name' => 'العلمين'],
            ['governorate_id' => 23, 'name' => 'الضبعة'],
            ['governorate_id' => 23, 'name' => 'النجيلة'],
            ['governorate_id' => 23, 'name' => 'سيدي براني'],
            ['governorate_id' => 23, 'name' => 'السلوم'],
            ['governorate_id' => 23, 'name' => 'سيوة'],
            ['governorate_id' => 23, 'name' => 'مارينا'],
            ['governorate_id' => 23, 'name' => 'الساحل الشمالى'],
            ['governorate_id' => 24, 'name' => 'الأقصر'],
            ['governorate_id' => 24, 'name' => 'الأقصر الجديدة'],
            ['governorate_id' => 24, 'name' => 'إسنا'],
            ['governorate_id' => 24, 'name' => 'طيبة الجديدة'],
            ['governorate_id' => 24, 'name' => 'الزينية'],
            ['governorate_id' => 24, 'name' => 'البياضية'],
            ['governorate_id' => 24, 'name' => 'القرنة'],
            ['governorate_id' => 24, 'name' => 'أرمنت'],
            ['governorate_id' => 24, 'name' => 'الطود'],
            ['governorate_id' => 25, 'name' => 'قنا'],
            ['governorate_id' => 25, 'name' => 'قنا الجديدة'],
            ['governorate_id' => 25, 'name' => 'ابو طشت'],
            ['governorate_id' => 25, 'name' => 'نجع حمادي'],
            ['governorate_id' => 25, 'name' => 'دشنا'],
            ['governorate_id' => 25, 'name' => 'الوقف'],
            ['governorate_id' => 25, 'name' => 'قفط'],
            ['governorate_id' => 25, 'name' => 'نقادة'],
            ['governorate_id' => 25, 'name' => 'فرشوط'],
            ['governorate_id' => 25, 'name' => 'قوص'],
            ['governorate_id' => 26, 'name' => 'العريش'],
            ['governorate_id' => 26, 'name' => 'الشيخ زويد'],
            ['governorate_id' => 26, 'name' => 'نخل'],
            ['governorate_id' => 26, 'name' => 'رفح'],
            ['governorate_id' => 26, 'name' => 'بئر العبد'],
            ['governorate_id' => 26, 'name' => 'الحسنة'],
            ['governorate_id' => 27, 'name' => 'سوهاج'],
            ['governorate_id' => 27, 'name' => 'سوهاج الجديدة'],
            ['governorate_id' => 27, 'name' => 'أخميم'],
            ['governorate_id' => 27, 'name' => 'أخميم الجديدة'],
            ['governorate_id' => 27, 'name' => 'البلينا'],
            ['governorate_id' => 27, 'name' => 'المراغة'],
            ['governorate_id' => 27, 'name' => 'المنشأة'],
            ['governorate_id' => 27, 'name' => 'دار السلام'],
            ['governorate_id' => 27, 'name' => 'جرجا'],
            ['governorate_id' => 27, 'name' => 'جهينة الغربية'],
            ['governorate_id' => 27, 'name' => 'ساقلته'],
            ['governorate_id' => 27, 'name' => 'طما'],
            ['governorate_id' => 27, 'name' => 'طهطا'],
            ['governorate_id' => 27, 'name' => 'الكوثر'],
        ];

        collect($cities)->chunk(100)->each(function (Collection $chunk) {
            DB::table('cities')->insert($chunk->toArray());
        });
    }
}
